import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import { normalizePointsMetadata, normalizePointsPage, pointsQuery, getPointsMetadata, getPointsPage } from './points-data.mjs';
import seed from '../data/points-seed.mjs';

const year = String(new Date().getFullYear());
const week = '第三十八周(09月14日至09月20日)';
const weeks = { code: 0, data: { week: [{ label: '第三十八周', value: week }] } };
const groups = { code: 0, data: [{ label: 'U10', value: 'U10' }, { label: 'U12', value: 'U12' }] };
const meta = normalizePointsMetadata(weeks, groups, year);
const query = pointsQuery(new URLSearchParams(), meta);
const row = { athleteName: '测试选手', organName: '测试俱乐部', athleteId: 111, athleteCode: 'PRIVATE', memberInfo: { birthday: 'PRIVATE' }, totalRank: 57, totalPoints: '321.5', season: year, gender: 'M', weapon: 'F', groupCode: 'U10', week: '第三十八周', specificDate: `${year}-09-26` };
const raw = { code: 0, data: { total: 1, current: 1, records: [row] } };
const normalized = normalizePointsPage(raw, query);
assert.equal(normalized.rows[0].rank, 57, 'search must preserve official rank');
assert.equal(normalized.rows[0].points, 321.5);
assert.doesNotMatch(JSON.stringify(normalized), /PRIVATE|memberInfo|birthday|athleteCode/);
assert.throws(() => normalizePointsPage({ code: 0, data: null }, query));
assert.throws(() => normalizePointsPage({ code: 0, data: { total: 1, records: [] } }, query));
assert.throws(() => normalizePointsPage({ code: 0, data: { total: 1, records: [{ ...row, weapon: 'E' }] } }, query));
assert.throws(() => normalizePointsPage({ code: 0, data: { total: 1, records: [{ ...row, week: '第三十七周' }] } }, query));
assert.throws(() => normalizePointsPage({ code: 0, data: { total: 1, records: [{ ...row, totalPoints: null }] } }, query));
assert.equal(normalizePointsPage({ code: 0, data: { total: 0, records: [] } }, query).rows.length, 0, 'confirmed empty must differ from null/error');
for (const p of ['weapon=X', 'groupCode=U6', 'current=-1', 'current=501', 'week=fake', 'season=1900']) assert.throws(() => pointsQuery(new URLSearchParams(p), meta));
let calls = 0;
const options = { sourceJson: async path => { calls++; return path.includes('getWeek') ? weeks : path.includes('groupcode') ? groups : raw; } };
await getPointsMetadata(options);
const [one, two] = await Promise.all([getPointsPage(new URLSearchParams('q=test'), options), getPointsPage(new URLSearchParams('q=test'), options)]);
assert.equal(one.rows[0].rank, two.rows[0].rank);
assert.equal(calls, 3, 'concurrent same query must share one upstream request after metadata');
await assert.rejects(getPointsPage(new URLSearchParams('q=never-cached'), { sourceJson: async () => { throw new Error('offline'); } }), /暂不可用/);
assert.equal(Object.keys(seed.pages).length, seed.metadata.groups.length * 6, 'release seed must cover every published group/gender/weapon first page');
assert.doesNotMatch(JSON.stringify(seed), /birthday|memberInfo|athleteCode|photoUrl/);
for (const page of Object.values(seed.pages)) {
  assert.equal(page.query.week, seed.metadata.weeks[0].value);
  assert.ok(page.rows.length <= 20);
  assert.ok(page.rows.every(row => Number.isFinite(row.points) && row.rank >= 1));
}
const fallback = await getPointsPage(new URLSearchParams('groupCode=U12'), { sourceJson: async () => { throw new Error('offline'); } });
assert.equal(fallback.cacheStatus, 'stale');
assert.equal(fallback.query.groupCode, 'U12');
assert.equal(fallback.query.week, week);
const explicit = await getPointsPage(new URLSearchParams({ season: seed.metadata.season, week: seed.metadata.weeks[0].value, q: 'explicit-week-test' }), options);
assert.equal(explicit.metadataStatus, 'reference', 'explicit published weeks must not wait on another upstream directory request');

const page = { innerHTML: '', querySelector: () => null, querySelectorAll: () => [] };
const context = vm.createContext({ document: { querySelector: () => page }, Date, console, AbortSignal, URLSearchParams, escapeHtml: value => String(value ?? '').replaceAll('<','&lt;').replaceAll('"','&quot;'), openHomeSearch: () => {} });
vm.runInContext(await readFile(new URL('../web/points.js', import.meta.url), 'utf8'), context);
context.result = normalized; context.meta = meta;
vm.runInContext('pointsUi.metadata=meta; pointsUi.query.week=meta.weeks[0].value; pointsUi.result=result; drawPointsPage();', context);
assert.match(page.innerHTML, /第 57 名/);
assert.match(page.innerHTML, /321.5/);
assert.match(page.innerHTML, /查看官方积分来源/);
vm.runInContext("pointsUi.loading=true; drawPointsPage();", context);
assert.doesNotMatch(page.innerHTML, /测试选手/, 'old results must be hidden during filter loading');
vm.runInContext("pointsUi.loading=false; pointsUi.error='offline'; drawPointsPage();", context);
assert.match(page.innerHTML, /重新加载/);
assert.doesNotMatch(page.innerHTML, /测试选手/);
// Resolve two filter requests in reverse order: late old responses cannot overwrite the latest group.
const deferred = [];
context.fetch = () => new Promise(resolve => deferred.push(resolve));
const first = vm.runInContext('loadPointsPage()', context);
const second = vm.runInContext("pointsUi.query.weapon='E'; loadPointsPage()", context);
deferred[1]({ ok: true, json: async () => ({ ok: true, ...normalized, rows: [{ ...normalized.rows[0], name: '新筛选' }] }) });
await second;
deferred[0]({ ok: true, json: async () => ({ ok: true, ...normalized }) });
await first;
assert.match(page.innerHTML, /新筛选/);
assert.doesNotMatch(page.innerHTML, /测试选手/);
console.log('official points: scope/week integrity, privacy, ranking, empty/error, cache dedup and UI race tests passed');
